export DS_ACCOUNT_1=p__goffi,Pedrohg31#
export DS_ACCOUNT_2=DIGITALSOULOFICIAL,DigitalS@ul1324@
export DS_ACCOUNT_3=VITALSOUL_OFC,DigitalS@ul1324@
export DS_ACCOUNT_4=AROMASOUL_OFC,DigitalS@ul1324@
export DS_ACCOUNT_5=DIGITALSOUL_ELETRONICOS,DigitalS@ul1324@